### ISSUE TITLE
Error: The "mkdocs-literate-nav" plugin is not installed

### ISSUE THREAD

**Issue by fergven** [oprypin/mkdocs-literate-nav#1]
I've installed the mkdocs-literate-nav plugin in my docker image (see image layer 29):
https://hub.docker.com/layers/132154017/fergven/mkdocs-vaas/latest/images/sha256-218048b1ca0c074735c8376e0d9b436db8835146477c3f63153a884f62248b2e?context=explore

My other plugins are working from my docker image.

In my mkdocs.yml, I've got this:
```yaml
plugins:
  - search
  - mkdocs-literate-nav:
      nav_file: SUMMARY.md
```

I've created the SUMMARY.md file and have populated it.

When I try to build or serve my mkdocs site, I get the following:
```
INFO    -  Building documentation...
ERROR   -  Config value: 'plugins'. Error: The "mkdocs-literate-nav" plugin is not installed

Aborted with 1 Configuration Errors!
```

I've also been unsuccessful running this outside of a docker image with just a straight `pip install`.

What am I doing wrong?

**Comment by oprypin** [comment]
Sorry, apparently that's a mistake in my README. The plugin's entry point installs as `literate-nav`, not `mkdocs-literate-nav`.

```yaml
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
```
