### ISSUE TITLE
Does mkdocs-literate-nav support horizontal tab navigation?

### ISSUE THREAD

**Issue by rohinimuralidharan** [oprypin/mkdocs-literate-nav#11]
Hi!
This plugin works well with a well-defined SUMMARY.md file, but doesn't display the nav in horizontal tabs as defined in my yml file. I am using Material theme. Could you please clarify if I am missing something? Also, could you please tell me if I can have both the index.md that refers to the home.html and the SUMMARY.md in the root folder? Thank you!

```yaml
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md  
```
