### ISSUE TITLE
Funny/weird: using literate-nav strips one slash from https:// in nav links

### ISSUE THREAD

**Issue by pawamoy** [oprypin/mkdocs-literate-nav#8]
See https://github.com/mkdocstrings/mkdocstrings/issues/337

It seems to happen only when the literate-nav plugin is activated, even when there's no SUMMARY.md file in the docs.

Here's the nav:

```yaml
nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage:
  - usage.md
  - Theming: theming.md
  - Handlers:
    - handlers/overview.md
    - Python: handlers/python.md
    - Crystal: https://mkdocstrings.github.io/crystal/
  - Troubleshooting: troubleshooting.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Author's website: https://pawamoy.github.io/
```

Looking at the built site, the link appear as `https:/pawamoy.github.io/` and `https:/mkdocstrings.github.io/crystal/` (note the single slash in `https:/`).
It's a bummer because somehow my browser (firefox) fixes it locally, but not when accessing the pages on github.io. Online, the browser ends up directing to https://mkdocstrings.github.io/pawamoy.github.io and https://mkdocstrings.github.io/mkdocstrings.github.io/crystal, which do not exist of course.

I'll try to read the code and guess what's happening here :slightly_smiling_face:
